### ISSUE TITLE
Feature: Merge Projects

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#15]
I'm not sure what this means but I am thinking if this has something to do with merging projects which are files composing of portions of the Bible text say for example, a project for the texts for Psalms, Genesis, etc. If this is that, then this must also be a very good feature for it will help more people get involved on a major translation or association project like what I'm doing by dividing the work by books or book chapters of the Bible. Once all the project pieces are done then the merge function will combine all the project files into one for exporting into either the .nt, .ot or .ont modules.

**Comment by rubiot** [comment]
Yes, that's the idea, to allow collaboration. I ended up implementing this as a [standalone tool](https://github.com/rubiot/iBibliaMergeTool). Interface is still Portuguese-only, though. I should remove this menu entry.

**Comment by malayangbiblia** [comment]
Looking forward to try this one too.
