### ISSUE TITLE
Question: How does adding notes work? Say I want to add a translator's note regarding a particular word within a verse

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#18]
Its easy to put a note at the bottom but my question is how can it be tagged with a superscript on the final Bible module?

**Comment by rubiot** [comment]
Everything you put into the comments textbox will be exported as a single note at the end of the verse **if** you check the option **Export comments as translator notes** in the export dialog. Feel free to use tags to add formatting to your notes (`<i></i>` for italics, `<b></b>` for bold, etc.). Does that answer your question?

**Comment by malayangbiblia** [comment]
Ok. How about if I have 3 notes for 3 different words in the verse? Does iBiblia have the ability to distinguish my 3 separate notes using superscript characters?

**Comment by rubiot** [comment]
No. You can add a single note that will be displayed to the end of the verse in theWord. But you can format your note to reference as many words as you want. Several Bible modules do so. Something along the lines of:

* **word1**: blah blah blah
* **word2**: blah blah blah

I thought of implementing support for word-anchored notes in iBiblia. But I didn't find the time and motivation to do it until now, considering there's an easy workaround.

**Comment by rubiot** [comment]
I've opened a suggestion to add word-level comments (#26).
