### ISSUE TITLE
Random automatic associations occur on a verse causing abort pop-up to appear

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#20]
I had a weird experience last night when iBiblia went weird after it froze, it showed the classic warning in Portuguese with about 50 lines and all I understood was Matt. 1:1. Then I kept on restarting the app for about 7 times still with the same error message, and then I realized that iBiblia is telling me to check Matt 1:1. To my surprise after going to Matt 1:1, I found out that there were like 3 to 4 words that were automatically associated. So I clicked the erase association for the current verse icon, saved the file and the problem was gone. I remember adding a new reference bible module before this happened. It happened again then I realized that the reference window was not showing. I tried to expand it thus scroll bars disabled. The crash stopped.

**Comment by rubiot** [comment]
> To my surprise after going to Matt 1:1, I found out that there were like 3 to 4 words that were automatically associated.

This shoudn't happen unless you've checked the option _"Automatically auto-associate verses"_ or clicked the _Auto-associate_ button.

> I tried to expand it thus scroll bars disabled. The crash stopped.
You can confirm that you were using v1.0.0.47 or v1.0.0.48 at the time this happened? Otherwise, there can be a remaining corner case I didn't handle.

**Comment by malayangbiblia** [comment]
> This shoudn't happen unless you've checked the option "Automatically auto-associate verses" or clicked the Auto-associate button.

> 

No, its not checked.

> You can confirm that you were using v1.0.0.47 or v1.0.0.48 at the time this happened? Otherwise, there can be a remaining corner case I didn't 

> handle.

I was using the latest version.

**Comment by rubiot** [comment]
Hopefully this is fixed in the latest [release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.50).
