### ISSUE TITLE
Feature Request: Turn on Always-on-Top option

### ISSUE THREAD

**Issue by malayangbiblia** [rubiot/ibiblia#21]
I think this is an easy one. I always want iBiblia to be on top of theWord when I'm working. Hope you will consider this tiny request. I tried using a couple of  3rd party apps that make this option possible with any running program, but it seems that only iBiblia doesn't accept the command/script.

**Comment by malayangbiblia** [comment]
Thanks my friend. I just downloaded the new build! I was watching you!

**Comment by rubiot** [comment]
haha. You're fast!

**Comment by malayangbiblia** [comment]
It will be a great day tomorrow. Good night bro! Happy weekend and thanks a lot!

**Comment by rubiot** [comment]
You're welcome! Have a great weekend.
