### ISSUE TITLE
Feature Request: Autosave changes when clicking the Navigation Buttons or Bible Tree

### ISSUE THREAD

**Issue by malayangbiblia** [rubiot/ibiblia#22]
I know these are just little improvement to an already cool app and don't really fix a serious problem but in a work like this, dealing with 31k verses, it means a lot. The app always asks (pops up) if I want to make the changes I made on the destination text verse which I always do (as I am working on literally every verse for the translation work). If I didn't I can go back and edit the current verse anytime. It takes 2 more steps to save the verse which I think isn't necessary. So I wish that when I'm done editing the destination text and I want to proceed to the next verse, I just need to click the nav button or anywhere in the Bible tree to save my latest changes. Thank you.

**Comment by rubiot** [comment]
Feature available in the [latest release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.49).
