### ISSUE TITLE
Switching to a different project (recent files) disables the navigation tree

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#29]

**Comment by rubiot** [comment]
Not reproducible here with v1.0.0.52. There must have to have some condition I do not have here.

**Comment by rubiot** [comment]
OK. I was able to reproduce it here now. I don't know why it worked before...

**Comment by rubiot** [comment]
Fixed in the latest release.

**Comment by openbibles** [comment]
Yes it is. Sweet!
