### ISSUE TITLE
Changing the font colors 

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#30]
I can see that the settings give the users options to make changes in the fonts. Everything else works, except that the custom colors.

**Comment by rubiot** [comment]
Yes, that's on purpose. Today colors are used to distinguish between associated/non-associated words (black/gray). If I allow the user to change the font colors this difference would be broken, and would have to be rethought.

**Comment by openbibles** [comment]
I see.

**Comment by openbibles** [comment]
This isn't too important.
