### ISSUE TITLE
Add option to choose what is synchronized with theWord dictionaries

### ISSUE THREAD

**Issue by rubiot** [rubiot/ibiblia#31]
When the user clicks a word, iBiblia only synchronizes theWord dictionaries to the word Strong's number. It would be very useful to be able to synchronize instead to the lemma, morphology or the word itself. This can be an option in the Options menu.

![image](https://user-images.githubusercontent.com/8127450/52542663-53ba5280-2d89-11e9-8841-c19af2a0c938.png)

**Comment by openbibles** [comment]
Looks cool, Bro. But honestly, I don't know where I could make use of that.

**Comment by rubiot** [comment]
Well, I'm missing this for some time. There are some very useful dictionaries that are not indexed by Strong's numbers.

**Comment by jgkoehn** [comment]
Yes I would like this as well I have several dictionaries this way.

**Comment by jgkoehn** [comment]
I would add the possibility for the user to have all searched, strongs, morph, lemma, and actual in the users chosen order.

**Comment by rubiot** [comment]
The problem is iBiblia doesn't know if a search succeed or not, so it makes no sense to make multiple-level searches.

**Comment by jgkoehn** [comment]
This is true-individual options makes more sense

**Comment by jgkoehn** [comment]
What if left click is strongs, right click morphology, left click + ctrl lemma, left click + alt is actual word. Unless these are already used. If they are perhaps like what you have in the picture with the option to change them out via ctrl + s goes to strongs, ctrl + m goes to morphology, ctrl + l to lemma, ctrl + a to actual

**Comment by rubiot** [comment]
Or maybe have a word context menu with entries for each option.

**Comment by rubiot** [comment]
On second thought, I works beautifully if I send everything to theWord - morphology, lemma and Strong#. This works because each dictionary will have only one of them, so they all synchronize to the correct entry. So there's no need to add options for these.

Done, will be in the next release.

**Comment by openbibles** [comment]
Great! Please also update the wiki for this new feature. Thanks!

**Comment by rubiot** [comment]
Done.
