### ISSUE TITLE
Program does not load a .ot file

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#32]
I'm trying to make an OT project but it seems to only load .ont and .nt modules.

**Comment by rubiot** [comment]
It should import .ot files without problems. I've fixed a bug concerning this in v.1.0.0.53. Are you using this version?

**Comment by openbibles** [comment]
Always the latest version. How come the open file dialog box on the file types section only provides .ont and .nt so that the .ot files won't even show up in the directory section. 
![image](https://user-images.githubusercontent.com/46296587/52996341-4a4f7b00-3458-11e9-9120-0e57d5e4974a.png)

**Comment by rubiot** [comment]
You're right. I was testing the importation for an existing project. Fixed.

**Comment by openbibles** [comment]
Thanks bro!
