### ISSUE TITLE
Feature Request: Ability to associate both Hebrew and Greek Tagged texts on the same Destination Text for .ot projects

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#35]
I was just thinking if it would be a great idea to show both the Hebrew and the Greek Lemmas of OT words in theWord. This I think would be an awesome resource for every Bible student.

**Comment by jgkoehn** [comment]
If you want to have English and both (Two steps perhaps) Just Hebrew and Greek then 1 step I believe.
English with Hebrew/Greek
Step 1. Source Hebrew, Destination English --- Associate the text
Step 2. Source Greek, Destination (Bible made from step 1) --- Associate the text 

Hebrew with Greek
Source Hebrew Destination Greek -- Associate the text

**Comment by jgkoehn** [comment]
I think the hard part would be building the Hebrew/Greek version. Hard but possible.

**Comment by rubiot** [comment]
Another fundamental problem is that the Greek LXX doesn't align perfectly to the Hebrew. Having said that, maybe a resource like [this](http://ccat.sas.upenn.edu/gopher/text/religion/biblical/parallel/) could serve as a starting point.

**Comment by openbibles** [comment]
> 
> 
> If you want to have English and both (Two steps perhaps) Just Hebrew and Greek then 1 step I believe.
> English with Hebrew/Greek
> Step 1. Source Hebrew, Destination English --- Associate the text
> Step 2. Source Greek, Destination (Bible made from step 1) --- Associate the text
> 
> Hebrew with Greek
> Source Hebrew Destination Greek -- Associate the text

Ya, That's it! Thanks.

**Comment by openbibles** [comment]
> 
> 
> Another fundamental problem is that the Greek LXX doesn't align perfectly to the Hebrew. Having said that, maybe a resource like [this](http://ccat.sas.upenn.edu/gopher/text/religion/biblical/parallel/) could serve as a starting point.

We'll, I thought about that also. The decision is up to the editor which source text he/she prefer's, the LXX or the Masoretic Hebrew. Probably, there's going to be 2 versions, 1 from LXX and the other from the MT.

**Comment by openbibles** [comment]
> 
> 
> Another fundamental problem is that the Greek LXX doesn't align perfectly to the Hebrew. Having said that, maybe a resource like [this](http://ccat.sas.upenn.edu/gopher/text/religion/biblical/parallel/) could serve as a starting point.

Hmmm... "ο θεός" is missing in Genesis 3:11 and from all theWord official LXX module. ABP has it and the scanned copy of the LXX, though.

**Comment by rubiot** [comment]
Maybe you're using a different critical edition. I'm no specialist, but I know there's at least a couple of them. [This](http://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxvar/1Pentateuch/01Gen.html) CCAT resource may be of your interest, it lists all variants.

**Comment by openbibles** [comment]
> 
> 
> Maybe you're using a different critical edition. I'm no specialist, but I know there's at least a couple of them. [This](http://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxvar/1Pentateuch/01Gen.html) CCAT resource may be of your interest, it lists all variants.

This is nice bro! Thanks for the link. I found what I was looking for...very interesting.

**Comment by rubiot** [comment]
Getting back to the requested feature, what exactly do you have in mind?

**Comment by openbibles** [comment]
> 
> 
> Getting back to the requested feature, what exactly do you have in mind?

Thanks for asking,
1. I will go back to my first motivation why I tag my translation- to check accuracy from the Original Text/s with any other language translation. 

2. Again, in translation, having the understanding that there are variations between the LXX and the MT, but for the serious student of the Bible the variations if taken in the right perspective might even complement each other instead of oppose each other in understanding the given passage. Example of this are the 4 Gospel accounts.

3. If someone will do this with a given translation, we may be able to remove the dividing line (if there is such) between the parties that side with either the Greek OT (Eastern Orthodox) or the Hebrew OT (Western) as the best source to use for study. I deem it best to use both not either, or. 

4. To apply this, I'm planning to produce a Tagalog OT based on both Hebrew and LXX particularly in passages where they differ in words. That is my plan but how to do about it I still have to wait, I'm only starting my journey into the LXX so let's see what happens. Most probably this is how I will implement this. If the passage or word is found in both Greek and Hebrew Texts then those will be tagged with both, but if the passage is only found in the Greek text then only Greek codes/words will be tagged. It goes the same way with the passages that are only found in the Hebrew Text.

**Comment by openbibles** [comment]
> 
> 
> If you want to have English and both (Two steps perhaps) Just Hebrew and Greek then 1 step I believe.
> English with Hebrew/Greek
> Step 1. Source Hebrew, Destination English --- Associate the text
> Step 2. Source Greek, Destination (Bible made from step 1) --- Associate the text
> 
> Hebrew with Greek
> Source Hebrew Destination Greek -- Associate the text

Guys, I tried this but it didn't work. I tried using the tagged KJV as my destination and the tagged LXX as my source text. The end result is still based on the source. A Greek tagged KJV Old Testament! Lol. But you know, I realized something. Do you think its worth the effort if the KJV is tagged purely in Greek? I don't know what would be the implications of this or if its even possible w/o compromising the integrity of the KJV and to find all the KJV OT words in the LXX.

**Comment by openbibles** [comment]
I did it! I figured out that I just need to make some

> 
> 
> > If you want to have English and both (Two steps perhaps) Just Hebrew and Greek then 1 step I believe.
> > English with Hebrew/Greek
> > Step 1. Source Hebrew, Destination English --- Associate the text
> > Step 2. Source Greek, Destination (Bible made from step 1) --- Associate the text
> > Hebrew with Greek
> > Source Hebrew Destination Greek -- Associate the text
> 
> Guys, I tried this but it didn't work. I tried using the tagged KJV as my destination and the tagged LXX as my source text. The end result is still based on the source. A Greek tagged KJV Old Testament! Lol.

I did it! I just made some changes on the Destination Text (Tagged KJV) tagged it in iBiblia using LXX as source then made a little adjustment to the final file. 

![image](https://user-images.githubusercontent.com/46296587/55126562-56f67b80-5148-11e9-86c2-bf57d6529263.png)

**Comment by jgkoehn** [comment]
Would it be possible to have Hebrew or Greek be the base instead of English?

**Comment by openbibles** [comment]
> 
> 
> Would it be possible to have Hebrew or Greek be the base instead of English?
Of course. iBiblia is simply a Bible copying app for TW. We tell it what to copy from one Bible to another.
