### ISSUE TITLE
Feature Request: Start from scratch on destination

### ISSUE THREAD

**Issue by jgkoehn** [rubiot/ibiblia#38]
When creating a new project that one could start from scratch on creating their own text based off of the source, and reference editions that then would be ordered to source. (Thanks Rubio for explaining how to do this through a work around.)

**Comment by rubiot** [comment]
Just documenting it : the workaround mentioned above is to load any destination text and then clear it using the "Clear Text" button on the project settings dialog.

**Comment by rubiot** [comment]
Please check the newest release.

**Comment by jgkoehn** [comment]
It loads nicely into a start from scratch project thank you!

**Comment by jgkoehn** [comment]
I seem to be missing my strongs in my source now. It is the same source I used for another project and I believe same source verse.rules.

**Comment by jgkoehn** [comment]
I see what happened I applied a verse rule and shouldn't have
