### ISSUE TITLE
Feature Request: Translation memory (include phrases)

### ISSUE THREAD

**Issue by jgkoehn** [rubiot/ibiblia#44]
This would just be a possible improvement on Translation memory in that when a phrase has been associated in source that a phrase would be included in translation memory besides just single words.

**Comment by rubiot** [comment]
This should be there already. Have you tried it?

**Comment by jgkoehn** [comment]
I'll have to try again. o Christos in the greek side of the source text kept coming up as either o or Christos but not as a whole perhaps this is intended.

**Comment by openbibles** [comment]
> 
> 
> I'll have to try again. o Christos in the greek side of the source text kept coming up as either o or Christos but not as a whole perhaps this is intended.

Did you use Shift+CTRL+left clicked all the associated words? Memory data will show up once you hit the save button.
