### ISSUE TITLE
Feature Request: Button "Send Rubio some Pizza!"

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#45]
This would be an awesome feature, do you think?
Then you have to put in here your delivery address a set of numbers from the Pizza stores near you. Don't worry we won't send you a bomb!

**Comment by openbibles** [comment]
Sorry lets get serious now...

**Comment by rubiot** [comment]
Not a bad idea... haha

**Comment by openbibles** [comment]
> 
> 
> Not a bad idea... haha

Seriously, you should put it there. It's the only way we can say thank you. Also put in there send milk or diapers to baby Rubio Jr. haha.
