### ISSUE TITLE
Choose what or what not to associate: Strongs, and/or Morphology and/or Source Text

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#49]
There are modules that are tagged differently like, the LXXM (Morphology only), and some only with Strongs and no Morphology. I was thinking if a feature like this will help fix these so we don't always have to look for an almost complete tagged source text which are rare to start with.

**Comment by jgkoehn** [comment]
Sounds like a good idea

**Comment by rubiot** [comment]
iBiblia doesn't require Strong's nor morphology tags. You could even associate two completely untagged texts.
When you associate two words, iBiblia doesn't care what tags they have, but it stores only the relationship you've stablished between them. Only when you export the association to a theWord module it checks the options to know what tags should be exported.

**Comment by openbibles** [comment]
Ghee...I didn't realize its already built in. 
![image](https://user-images.githubusercontent.com/46296587/54860495-c558c980-4d55-11e9-952a-a7e13b4b7ee6.png)
