### ISSUE TITLE
Random crash when using navigation green buttons

### ISSUE THREAD

**Issue by malayangbiblia** [rubiot/ibiblia#5]

**Comment by malayangbiblia** [comment]
I notice that it only happen when I skipped clicking the 'associated' button.

**Comment by rubiot** [comment]
I still wasn't able to reproduce this using your project. Please let me know if you find any other clues.

**Comment by malayangbiblia** [comment]
Next time this happens, I will take not of the verse I'm working on and send you the file.

**Comment by rubiot** [comment]
I think I pinpointed this bug. It happened only when the verse edit was too small so it had to enable the scrollbars. It didn't happen here before because my window was bigger. The fix will soon be available in a next release.

**Comment by rubiot** [comment]
Please check the new [release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.47), which should fix this bug.
