### ISSUE TITLE
Feature Request: Context panel

### ISSUE THREAD

**Issue by jgkoehn** [rubiot/ibiblia#50]
A Panel that displays a user set amount of the verses before the one you are translating of already translated verses.
Perhaps another panel a user set amount of verses after the ones you are translating of translated verses if they exist.
This is to help keep things with in their context.

**Comment by openbibles** [comment]
This is good but do you think that just syncing it with theWord Bible view in the background is much better than doing it here+ you can see all your dictionaries and commentaries about the verse you are translating? Just set always on top so that iBiblia can work side by side with theWord without losing your focus.

**Comment by jgkoehn** [comment]
I see what you mean. Hmms, I guess I've also been using iBiblia by itself but I could see this as diplicate woek

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rubiot** [comment]
I sometimes miss this for the destination text when I'm making changes to the text itself, and theWord doesn't have the updates yet. Any suggestions on how those context verses could be integrated to the current layout?

**Comment by jgkoehn** [comment]
Perhaps a popup with a user chosen amount 5 for example would display the previous 5 verses without worrying about chapter breaks etc. If the user is so inclined perhaps a negative number would show the verses following. Or vice versa -5 is the previous 5 is the following. This popup could either stay on or just popup.

**Comment by rubiot** [comment]
Please check the new [release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.61). I've added a new panel to the right in which the current chapter is always displayed. It can be resized or even hidden altogether using the mouse. Right-click the chapter view to open a context menu and configure the font and display mode (paragraph mode or verse-per-line).

Verse numbers are links, click them to go that verse. All chapter notes are available at the end of the chapter. Note numbers are links that lead to their text and back.

Any feedback is welcome.

**Comment by openbibles** [comment]
Wow. This feature rocks! Very helpful in doing translation projects. Love it!

**Comment by rubiot** [comment]
Yes, I use it all the time now. I wonder how I could work without it before... haha
