### ISSUE TITLE
Destination Text Strong's count enhancement

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#51]
I noticed that the Strong's count doesn't include the additional Strong's # associations from the Source text on the same word in the destination text. This is not a big deal but it would be more accurate to view if we change the formula of counting the Strongs in the Destination Text into total number of strongs associated per verse.

Example: 

In Destination Text: 

word1 when assoc. w/ G1 (Strongs#SourceText) = 1 strong's count
word2 assoc. w/ G2, word3 assoc. w/ G3 = 2 strong's counts

but,

word4 assoc. w/ G4 AND w/ G5 = 1 strong's count only.

I suggest if possible that we make the formula instead of:
Total Strong's count = 1G/1W + 1G/1W + 1G/1W + (1G*1G)/1W = 4 G/W or Strong's Count,
we do this,
Total Strong's count = 1G/1W + 1G/1W + 1G/1W + (1G+1G)/1W = 5 G/W or Strong's Count, 
where G is the Strong's Number associated with the given W (destination word).

Needless to say, that there are sometimes multiple words in the Greek that is only equivalent to one word in the destination text and the other way around. 

Sorry for the long explanation, but you know what I mean.

**Comment by jgkoehn** [comment]
This indeed would be helpful. Often like in ο Χριστος is only one in English. (Are you already doing this Rubio?)

**Comment by rubiot** [comment]
The fix will be in the next release.
