### ISSUE TITLE
Malachi 4:6 bug

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#55]
![image](https://user-images.githubusercontent.com/46296587/54872506-d8c06f00-4dff-11e9-92fe-35d9aae8509b.png)

![image](https://user-images.githubusercontent.com/46296587/54872521-132a0c00-4e00-11e9-9c4d-0673ccdcf2e3.png)

I'm getting random of these. Only happens when I update my source text. The last associated verse that was saved is being transferred to Malachi 4:6 source and destination text.

**Comment by openbibles** [comment]
Ok. I tried removing the blue font code in the destination and replaced the source. This time no errors.

**Comment by openbibles** [comment]
This happens first right after I replace source text. 
![image](https://user-images.githubusercontent.com/46296587/55459947-50be3e80-5623-11e9-9aca-f74d8bf168d4.png)

**Comment by openbibles** [comment]
I turned off "Auto-associate" and erased the associations. Then the error stopped.

**Comment by openbibles** [comment]
I think I found a work-around to avoid this bug. I have to restart iBiblia before I update my source text and it never happens again.

**Comment by rubiot** [comment]
Good. But I'll try and fix this later, anyway.

**Comment by openbibles** [comment]
> 
> 
> Good. But I'll try and fix this later, anyway.

This kindness is not required though much appreciated.

**Comment by openbibles** [comment]
False alarm. Bug still persists no matter what I do. There seem to be no work around to this but to fix it, bro. Thanks a lot!

**Comment by rubiot** [comment]
It seems that Malachi 4:6 ended up with some spurious associations in your project. Please do the following: go to this verse, click the eraser button (clear verse associations) and save your project. Then report back if the bug happens once again next time around.

**Comment by openbibles** [comment]
> 
> 
> It seems that Malachi 4:6 ended up with some spurious associations in your project. Please do the following: go to this verse, click the eraser button (clear verse associations) and save your project. Then report back if the bug happens once again next time around.

This usually is one of my work around. But it happens again after a while. I even tried deleting all the texts both in the source and the text windows so there is nothing to export/associate but it still happens.

**Comment by rubiot** [comment]
I was able to consistently reproduce a bug when loading a new text. It may be this one. The fix will be on the next release. Please report back if the bug persists.

**Comment by openbibles** [comment]
> 
> 
> I was able to consistently reproduce a bug when loading a new text. It may be this one. The fix will be on the next release. Please report back if the bug persists.

God bless you bro!

**Comment by rubiot** [comment]
I believe this is fixed in the new release. In case of any problem, please reopen the issue.

**Comment by openbibles** [comment]
> 
> 
> I believe this is fixed in the new release. In case of any problem, please reopen the issue.

Thanks, bro!
