### ISSUE TITLE
Enhanced Proofreading - ability to export: source, destination, ref1 and ref1 separately

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#56]
Hey Rubio, iBiblia never ceases to amaze me. Thanks for everything.

I'm currently helping our beloved mathetes in proof-reading his LXX and incidentally the Brenton's English version. I have to send him updates every time I see a correction so he could compare it with his file and do the necessary changes. It came to me that both modules have typo error of some kind. 

I think iBiblia can be an excellent proof-reading machine for theWord Bible modules. But it's only limited to the destination text. No one has the time to proof-read already published modules, but the fact still remains most of these modules aren't 100% typo free. Since iBiblia gives us option to see 4 modules at the same time, why don't we give it ability to update all 4 whenever necessary to save proofreading time. Then export separately the updated/revised text on-the-go. 

On the other hand, I can launch multiple instances of iBiblia to get this desired feature.

**Comment by openbibles** [comment]
Sorry I have no way to delete the post. I'm closing it now.

**Comment by rubiot** [comment]
You can edit all four texts already, but you cannot export all of them **yet**. Fortunately I've added this option some days ago :) It will be in the next release.

**Comment by openbibles** [comment]
Great! I didn't expect this to come out that soon.

**Comment by rubiot** [comment]
Please check the new [release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.61).

**Comment by rubiot** [comment]
Right-click an empty area of the verse and click "Export text to file...".
