### ISSUE TITLE
Auto-association converts ' to " inside the translation memory

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#57]
Any word associated by iBiblia which has apostrophe (') is replaced with a quotation (") mark in the translation memory. As a result, words like these won't work for auto-association.  

![image](https://user-images.githubusercontent.com/46296587/57506281-f1440480-732d-11e9-9ad1-af66ee548ca3.png)

Thank you, Brother, for continuously developing this awesome program!

**Comment by rubiot** [comment]
Fixed. It will be in the next release.
