### ISSUE TITLE
"Access Violation Crash" w/ OT projects in v.57

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#59]
Seems that the latest update (v.57) crashes OT projects. Everything is fine with the NT. 

![image](https://user-images.githubusercontent.com/46296587/58066421-ddb15d00-7bbb-11e9-88ee-63337b3a0dae.png)

![image](https://user-images.githubusercontent.com/46296587/58066447-f457b400-7bbb-11e9-84f7-dfc69437d756.png)

![image](https://user-images.githubusercontent.com/46296587/58066529-4ef11000-7bbc-11e9-8139-2994d9a49067.png)

![image](https://user-images.githubusercontent.com/46296587/58066573-76e07380-7bbc-11e9-9a30-f62cc2695bba.png)

**Comment by rubiot** [comment]
At what time the crash happens? When you're trying to associate two words?

**Comment by openbibles** [comment]
> 
> 
> At what time the crash happens? When you're trying to associate two words?

Not even. It happens anytime I click a word in the source text.

**Comment by rubiot** [comment]
Not reproducible here. Would you mind sending me your project?

**Comment by openbibles** [comment]
Here: https://github.com/openbibles/Septuagint-English-Interlinear/releases/download/EngLXX/LXXi.bib
I found out that it only happens when TheWord is running.

**Comment by rubiot** [comment]
Found it. I'll roll up a new release.

**Comment by openbibles** [comment]
Sorry bro, but the issue is still there even with v.58. Thanks!

**Comment by openbibles** [comment]
Fixed indeed!

**Comment by rubiot** [comment]
Good.
