### ISSUE TITLE
Effect of Editing A Destination Text To Succeeding Associations

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#61]
I now experience a significant number of words being wiped out from succeeding associated words in the destination text once I revise a word previously associated. In version .56, when I update a word in the destination text, only the affected text loses association, but now, as much as 10x the number of associated words are being wiped out once I update a single word in the destination text.

**Comment by openbibles** [comment]
It seems that this is not happening all the time. Will continue to observe.

**Comment by rubiot** [comment]
I believe this is fixed in [v1.0.0.60](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.60).

**Comment by openbibles** [comment]
Thanks bro that was fast! Bless you!

**Comment by openbibles** [comment]
Bug is still there. Still happens once in a while.

**Comment by rubiot** [comment]
Hmm, are you using vertical bars to split words?

**Comment by openbibles** [comment]
I don't know what you mean by split words but I never use vertical bar
character.
