### ISSUE TITLE
<_MORPH_> code shows up in MySword

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#62]
I'm just wondering if this code is necessary for tags to work coz it doesn't show up in TW, only in MySword at the end of line 1

![image](https://user-images.githubusercontent.com/46296587/60066349-6b431800-9739-11e9-9f0c-577f0f4114b5.png)

**Comment by rubiot** [comment]
This tag is needed for theWord. Without it theWord won't recognize morphology tags for modules which have no morphology tags in the first verse. But, knowing that MySword have no need for it, I guess it would be simple to omit this when exporting modules for this program.

**Comment by rubiot** [comment]
Please check the new [release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.61).

**Comment by openbibles** [comment]
Thanks!
