### ISSUE TITLE
Can I import a *.txt file into a project?

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#63]
Thanks for the #56! I've been thinking how I am able to make use of the exported text file since there is no tool available yet that directly converts a text to a bible module. But if iBiblia supports the importing of a UTF-8 text file, then text revision is going to step up to a whole new level. For example, I need to replace multiple instances of a word or correct multiple  but identical errors. I only need to export the file from iBiblia into a text and replace them all in Notepad+, save and reload it back into the project. Without this, users have to do it in Biblia manually typing each word verse by verse.

**Comment by rubiot** [comment]
You're most welcome! The thing here is: a theWord Bible module **is** a text file. Therefore you can import back an exported text (that's exactly why I added the export text feature). You only have to make sure you export it with the right extension (or change it before importing): _.ot_ for old testament, _.nt_ for new testament and _.ont_ for both testaments.

**Comment by openbibles** [comment]
Oh I see! Sorry, I got used to the drop down selection for .nt, .ot or .ont upon save. But I can see now that I could either override an existing file upon export and retain its extension or save a new one and just add .nt or .ot at the end of the filename. That's it.
