### ISSUE TITLE
Switching dictionary pop-up trigger

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#66]
Hi bro. hope you're doing fine!

Just like to ask if there is a shortcut key to switch from mouse hover to something else? I find myself constantly doing this because the mouse hover pop-up usually goes in the way during association but is very helpful during translation. So whenever I translate I use mouse hover, but when I associate words I use the second dictionary trigger. Or probably, the best way to approach this is to add these options to the toolbar icons in the future. Thanks!

**Comment by rubiot** [comment]
Well, maybe this gets some using, but I do translation (more like editing in my case) and association and the mouse hover popup doesn't get in my way. And I use the Ctrl+hover configuration. What configuration do you use? Alt+hover?

**Comment by openbibles** [comment]
I just use mouse hover when translating which is more efficient for me. I think I found a work around to this. If iBiblia is in the middle of the screen, chances are the pop-up is placed above the mouse pointer or below the mouse pointer. Only when it pops up above the mouse pointer that it blocks the rest of the words in the destination window (when associating not translating/editing). But if I put iBiblia right at the very top edge of the screen, all popups appear below the mouse pointer.

**Comment by rubiot** [comment]
![image](https://user-images.githubusercontent.com/8127450/77424747-64246580-6db0-11ea-8118-bbc63c9a70b3.png)
We already have three options in the Options menu. I guess adding a shortcut to switch shortcuts would be a bit too much. Would do you say, can I close this?

**Comment by openbibles** [comment]
Yes go ahead. I'm getting used with just mouse hover...

**Comment by rubiot** [comment]
Thanks!
