### ISSUE TITLE
Word lookup without Strong's/Morph Tags for English and Hebrew/Greek texts

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#70]
I just wish that words clicked in iBiblia can appear in theWord dictionaries to find definitions. This would be a great tool for translation work without having a tagged modules of Hebrew/Greek.

**Comment by openbibles** [comment]
Thank You!

**Comment by rubiot** [comment]
Feature available in [new release](https://github.com/rubiot/ibiblia/releases/tag/v1.0.0.61).
