### ISSUE TITLE
Additional Reference Text

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#73]
Hi Rubio, I pray for your safety and protection..!

As a translator, it's nice to see multiple references to understand the meaning of each word and how its being used in a micro-level. What I envision is to at least use two variations of the Greek text, one from source text and another from the reference and two other English translations. This is better than switching to theWord software all the time. But the problem I'm seeing is that the project file becomes bigger by adding more references. So probably, the best would be to keep it to max of 3 reference texts + source + destination. 

Thanks!

**Comment by rubiot** [comment]
Yes, the easiest and lightest way to have more reference texts would be sychronizing with theWord. I have a big screen and work with iBiblia and theWord side by side is quite comfortable. But I understand this could problematic with lower resolutions. But let me ask you something: do you know you can dettach any view from theWord making it a floating window, and then position it wherever you want in the screen?

Having said that, I could add one more referente text, but I fear this would make iBiblia too slow. The support for formatting and dictionary popup is quite sluggish and one more verse could be prohibitive on slower CPUs.

**Comment by openbibles** [comment]
Well, I can understand that. But say let's just do it as an option for heavy users like me..

The funny thing I don't want to tell you is that translation for me is a very immersive work intellectually and spiritually. Having 2 software windows in front of me is ok, but switching back and forth to 2 different interfaces w/ at least 5 multiple sections within the program is quite mentally/focus challenging. I don't see the floating window as a work around either. Man, how I wish iBiblia is built in to theWord! 

On the other hand, I don't see this as a necessity at the moment and should be in the low priority on your list if in case you consider it in the future.

**Comment by openbibles** [comment]
Just realized that the probability of using this is very small. Not worth effort...
