### ISSUE TITLE
Cannot navigate past to verse 99 on Psalms 119

### ISSUE THREAD

**Issue by rubiot** [rubiot/ibiblia#74]
![image](https://user-images.githubusercontent.com/8127450/77441818-9fcb2980-6dc8-11ea-9aae-c4f2b3e11bba.png)

**Comment by rubiot** [comment]
Fixed for new projects (will be available in v1.0.0.64). Existing projects with this problem unfortunately will have to be fixed manually. Here's how to do it:

1. Download an SQLite browser, for instance https://sqlitebrowser.org/dl/. It has a portable version that doesn't require installation;
2. Open your project (.bib file) in the SQLite browser. Close the project in iBiblia first if necessary;
3. Run the following SQL statement: ```update pares set pare_id = replace(pare_id, '.', ',') where pare_id like '%.%'```. It should display a message saying 77 rows were affected:
![image](https://user-images.githubusercontent.com/8127450/77443411-cf2e6600-6dc9-11ea-8e78-3ce44f4dcefe.png)
4.  Click the "Write changes" button and close the editor. Done!

**Comment by openbibles** [comment]
Thanks. It worked!

Bro. Edmund
https://malayangbiblia.wixsite.com/free
