### ISSUE TITLE
Words of Jesus in Red behaving differently than theWord

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#77]
Hi Rubio, Im currently doing this and I'm not yet expert on this area. I'm using "FR...Fr" code to format words in red, but I don't know if I need to do this on every verse if the whole chapter or passage should be in red. I tried doing verse by verse and it works. But if there's a shortcut to this, just let me know. Thanks!

**Comment by openbibles** [comment]
I realized that ibiblia allows multiple verses/passages applied using the standard code FR.(whole passage/multiple verses)..Fr. But it won't work when in TW(exported).

**Comment by rubiot** [comment]
Yes, unfortunately you have to add new tags for each verse. This is how theWord works.

**Comment by rubiot** [comment]
Wait, you're saying the chapter preview in iBiblia works with the tags spanning through several verses? In this case it would be a bug in iBiblia, because it should mimic the exact behavior of theWord.

**Comment by openbibles** [comment]
> 
> 
> Wait, are you saying the chapter preview in iBiblia works with the tags spanning through several verses? In this case it would be a bug in iBiblia, because it should mimic the exact behavior of theWord.

Yes. Thank you for clearing this up.

**Comment by rubiot** [comment]
Fixed. The correction will be on the next release.
