### ISSUE TITLE
Editing with Horizontal Scroll on

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#79]
I don't know if this is somehow related to #17 
Pls check my video: https://youtu.be/pi2XosFwbaY

**Comment by rubiot** [comment]
Good catch. I look into this later.

**Comment by rubiot** [comment]
I see your video isn't available anymore. The problem is I don't remember what was the problem exactly...

**Comment by rubiot** [comment]
Do you happen to remember?

**Comment by openbibles** [comment]
Hey, Bro.
Happy New Year!

Here's the video: https://youtu.be/A6wfHv27sI8

Bro. Edmund
https://malayangbiblia.wixsite.com/free

**Comment by rubiot** [comment]
Fixed. Correction will be on the next release.
