### ISSUE TITLE
Delay switching verses (compare view in theWord ON)

### ISSUE THREAD

**Issue by SalitaNgDiyos** [rubiot/ibiblia#82]
Hi Rubio,
Merry Christmas!
Just want to report this thing that when in sync mode with theWord and iBiblia, there seems to be a 5 seconds delay when switching verses when under compare mode in theWord.

**Comment by rubiot** [comment]
Hi, Edmund. I'm a bit late to wish you a Merry Christmas, but **happy New Year**! I'll check that.

**Comment by openbibles** [comment]
I think the extra seconds delay is caused by the option "save upon verse change" which I turn on all the time. I tried turning it of and the delay seems to disappear.

**Comment by rubiot** [comment]
Just to clarify, what are your sync options there?
![image](https://user-images.githubusercontent.com/8127450/104314829-bd34c580-54b8-11eb-9196-09f68611a6a4.png)

**Comment by openbibles** [comment]
The word to ibiblia sync is on

**Comment by SalitaNgDiyos** [comment]
I just upgraded my entire PC to AMD Ryzen 5600G DDR4 16GB RAM from AMD A8 7800 DDR3 16GB RAM and I noticed that all the lags were gone!
