### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by openbibles** [rubiot/ibiblia#86]
I remember once, we have this feature but now its gone. The footnotes were placed at the bottom of the context view with corresponding numbers for the translator's notes/comments. Could we put it back in the next release due to the fact that theWord has a poor footnoting feature for exporting chapters and verses. Also there is no way to export the subject headings of Bible modules or maybe I am missing something.

**Comment by rubiot** [comment]
This was an old renderer I'm not using anymore. I'm using the clickable notes now to better mimic the default theWord's behavior. It would be nice to have both options, but I'd have to redo it from scratch. I understand this is not a priority right now but I can keep it as a suggestion.

Having said that, I'm not sure you know, but you can have the behavior you want in theWord.
![image](https://user-images.githubusercontent.com/8127450/104127621-eb43c980-5341-11eb-8832-71fae277bf0a.png)

I'm not sure what you mean by "poor footnoting". You can select the whole chapter with Ctrl+A, copy and paste it in Microsoft Word, for instance, and keep all the notes as endnotes. Does this help?
![image](https://user-images.githubusercontent.com/8127450/104127709-7624c400-5342-11eb-94ce-65fea72e773c.png)

**Comment by openbibles** [comment]
Oh, my goodness! It's been there all along..
