### ISSUE TITLE
Interlinear without Destination

### ISSUE THREAD

**Issue by jonathangkoehn** [rubiot/ibiblia#98]
Is there a way to type in the destination text without having it exist already?
For example:
Source = BYZa
Destination = none

In the begining was the Word and the Word was with God . . .

Or would one just do this in the blank area?

**Comment by jonathangkoehn** [comment]
Ah I figured it out.
Just make a basically empty Bible, maybe title etc. and then put a single letter on every line that will have a verse.
Now you can just type in the destination text area after you delete the single letter.

**Comment by jonathangkoehn** [comment]
Would an option to select automake an empty text like this be possible?

**Comment by jonathangkoehn** [comment]
I sorta had it working but it errored out and crashed iBiblia. Also seems like my data got corrupted.

**Comment by rubiot** [comment]
Hi Jonathan,
You don't have to select a destination text, you can leave it empty and click OK.
![image](https://github.com/rubiot/ibiblia/assets/8127450/1a4771be-e27c-4885-a33a-b6d9b283995b)
